name: Bug Report
description: Report an error or unexpected behavior in the design system
title: '[Bug]: '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. Please complete the following information to help us reproduce and fix the issue.
        Please search open/closed issues before submitting. Someone might have asked the same thing before!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: |
        Example: The primary button does not display the correct color when dark theme is applied in tenant X
    validations:
      required: true

  - type: input
    id: reproduction-link
    attributes:
      label: Reproduction Link
      description: Please provide a link to a reproduction environment (StackBlitz, CodeSandbox, CodePen, etc.)
      placeholder: 'https://inditex.com/edit/...'
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe the error in '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: The button should display the primary theme color
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what is actually happening
      placeholder: The button displays a gray color instead of the primary color
    validations:
      required: true

  - type: dropdown
    id: tenant
    attributes:
      label: Tenant
      description: Which tenant does this issue occur in?
      options:
        - bershka
        - lefties
        - massimo-dutti
        - oysho
        - pull-and-bear
        - stradivarius
        - zara
        - zara-home
    validations:
      required: true

  - type: dropdown
    id: theme
    attributes:
      label: Theme
      description: Which theme does this issue occur with?
      options:
        - light
        - dark
        - both
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Affected Component
      description: Which component(s) from the design system are affected?
      placeholder: 'Button, Input, Card, etc.'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Design System Version
      description: Which version of the design system are you using?
      placeholder: '1.0.0'
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser(s) does this issue occur in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system does this issue occur on?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images here

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about the problem
      placeholder: |
        - Does the problem occur in production?
        - Is there a known workaround?
        - Browser console information?
