name: Feature Request
description: Suggest a new feature or enhancement for the design system
title: '[Feature]: [Component] '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a feature request!
        Please search open/closed issues before submitting. Someone might have asked the same thing before!

        **Title format**: [Feature]: [Component] Short description
        Example: [Feature]: Input - Add optional field indicator

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your request in one or two sentences
      placeholder: |
        Example: Add an "Optional" tag/label to Input components to clearly indicate non-required fields
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement/Justification
      description: Please provide valid reason(s) why this should be added to the design system
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution or API
      description: Please provide code snippets, gists, or links to the ideal design or API
      render: tsx
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New component
        - Component enhancement
        - New utility/hook
        - Theming improvement
        - Accessibility improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternative solutions have you considered before making this request?
      placeholder: |
        Example: I considered adding custom text after each label manually, but it's inconsistent and doesn't follow design system patterns.

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: What resources (links, screenshots, Figma designs, etc.) do you have to assist this effort?
      placeholder: |
        - Figma design: https://figma.com/...
        - Similar implementation: https://...
        - Screenshots or mockups
